/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/auth/connexion': RouteRecordInfo<'/auth/connexion', '/auth/connexion', Record<never, never>, Record<never, never>>,
    '/auth/inscription': RouteRecordInfo<'/auth/inscription', '/auth/inscription', Record<never, never>, Record<never, never>>,
    '/auth/reset-password/': RouteRecordInfo<'/auth/reset-password/', '/auth/reset-password', Record<never, never>, Record<never, never>>,
    '/auth/reset-password/[token]': RouteRecordInfo<'/auth/reset-password/[token]', '/auth/reset-password/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    '/compte': RouteRecordInfo<'/compte', '/compte', Record<never, never>, Record<never, never>>,
  }
}
